name: py39_bert_cpu # Name of the created environment
channels:                # Repositories to search for packages
- conda-forge
dependencies:            # List of packages that should be installed
- python=3.9             # Python
- py4j                   # used for KNIME <-> Python communication
- nomkl                  # Prevents the use of Intel's MKL
- pandas                 # Table data structures
- numpy                  # N-dimensional arrays
- pyarrow<8.0            # Arrow serialization
- protobuf<4.0           # Versions larger than 4.0 are incompatible with tensorflow-hub and bert-for-tf2
- tensorflow=2.8.1
- tensorflow-hub=0.12.0
- transformers=4.6.1
- sentencepiece          # Additional dependency for some zero-shot classification models
- termcolor=2.0.1
- setuptools<70          # setuptools 70.0 removed convert_path, which is used in the pip packages params-flow, py-params and bert-for-tf2 (this line can be deleted once the three pip packages are updated) (https://github.com/pypa/setuptools/blob/33afc112522057851eeaa016df7fdf774b3b1626/NEWS.rst#deprecations-and-removals)
- pip
- pip:
  - bert-for-tf2==0.14.9

